Import('env')


# List of sources:

TEST_SOURCES = Glob('*.cpp')

# Test script variables:

TEST_SCRIPT_NAME = 'lua++_tests'
LIB_NAME = 'lua++'
LIB_DIR = '#/build'
INCLUDES = [
    '#/include',
    '#/deps',
    LIB_DIR
]
DEPS = [
    LIB_NAME,
    'lua'
]

env.Append(CPPPATH=INCLUDES)


# Build testscript:

env.Program(target=TEST_SCRIPT_NAME, source=TEST_SOURCES, 
            LIBS=DEPS, LIBPATH=LIB_DIR)

