Import('env')

# List of sources:

LIB_SOURCES = Glob('*.cpp')

# Library variables:

LIB_NAME = 'lua++'  # (liblua++.a)
INCLUDES = [
    '#/include',
]

env.Append(CPPPATH=INCLUDES)

# Build library:

env.StaticLibrary(target=LIB_NAME, 
                  source=LIB_SOURCES)

